n1 = int(input('Primeiro valor: '))
n2 = int(input('Segundo valor: '))
n3 = int(input('Terceiro valor: '))
maior = max(n1, n2, n3)
menor = min(n1, n2, n3)
print(f'O menor valor digitado foi: {menor}')
print(f'O maior valor digitado foi: {maior}')